### ISSUE TITLE
PRGs crashing

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [MiSTer-devel/PET2001_MiSTer#1]
PRGs seem to be auto-injected fine and they show up in the LIST, but they all crash with errors when launched. It could be something I'm doing wrong?

Loading works, I run the program, and for some it shows a screen, but then I'll get "UNDEF'D STATEMENT ERROR IN 180" (or some other number)

**Comment by sorgelig** [comment]
yes, i see it's crashing. 
Probably some system/basic variables need to be set after injecting. I will check it.

I recommend to use TAP files. It's more natural way to load the apps. Fast TAP loading mode doesn't take much time.

**Comment by SmokeMonsterPacks** [comment]
Thanks! Please let me know what you find out. 

Do you have a recommended source for TAP files? The only type I've seen so far are .PRG.

**Comment by sorgelig** [comment]
i think TOSEC should have TAP files.

**Comment by SmokeMonsterPacks** [comment]
Thanks! Please let me know what you find out.

**Comment by SmokeMonsterPacks** [comment]
Thanks again.

**Comment by raparici** [comment]
Hi, I just created a pull request with the PRG injector fix. Now basic variables start pointer is set and programs get no corrupted during execution after injection.
