### ISSUE TITLE
Control registering as shift in page 0 (LDA 152, CMP #1 BEQ...)

### ISSUE THREAD

**Issue by fayep** [MiSTer-devel/PET2001_MiSTer#8]
I loaded a friend’s Galaga program he wrote at school and it worked... if I used CTRL as fire instead of SHIFT.  The instructions being used to test for SHIFT pressed are in the subject and in an emulator this is registered correctly as the shift key.  The keys are X to start, Z left, C right (C being held correctly overrides Z) and at the moment CTRL to fire (but it should be SHIFT).  He’s given me permission to upload the PRG for testing.  you load it and then run with SYS 4096 as it was written in assembly code.

[test.zip](https://github.com/MiSTer-devel/PET2001_MiSTer/files/6360424/test.zip)

Enjoy :)

**Comment by sorgelig** [comment]
This is intentional. CTRL is used as pure SHIFT. SHIFT key is also used as SHIFT but it modifies some shifted buttons to reflect the symbols on PC keyboard.
